# conda env create --file environment.yml
# mamba env create --file environment.yml
name: spectral_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - python=3.8
  - scikit-learn
  - seaborn
  